# Generated by Django 4.1 on 2022-08-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
