# Generated by Django 4.1 on 2022-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedfeatures',
            old_name='engine_v',
            new_name='carat',
        ),
        migrations.RenameField(
            model_name='requestedfeatures',
            old_name='body',
            new_name='clarity',
        ),
        migrations.RenameField(
            model_name='requestedfeatures',
            old_name='brand',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='requestedfeatures',
            old_name='engine_type',
            new_name='cut',
        ),
        migrations.RemoveField(
            model_name='requestedfeatures',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='requestedfeatures',
            name='model',
        ),
        migrations.RemoveField(
            model_name='requestedfeatures',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='requestedfeatures',
            name='year',
        ),
        migrations.AddField(
            model_name='requestedfeatures',
            name='depth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedfeatures',
            name='table',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedfeatures',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedfeatures',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedfeatures',
            name='z',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
