# Generated by Django 4.1 on 2022-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_requestedfeatures_clarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedfeatures',
            name='clarity',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='requestedfeatures',
            name='color',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='requestedfeatures',
            name='cut',
            field=models.CharField(max_length=25),
        ),
    ]
