# Generated by Django 4.1 on 2022-08-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jsonfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedprice',
            name='request_id',
        ),
        migrations.AddField(
            model_name='predictedprice',
            name='features_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='api.requestedfeatures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedfeatures',
            name='file_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.jsonfile'),
            preserve_default=False,
        ),
    ]
